apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: analytics
  name: analytics
  namespace: currently-working-on-db
spec:
  ports:
    - name: "4000"
      port: 4000
      targetPort: 4000
  selector:
    io.kompose.service: analytics
status:
  loadBalancer: {}
