apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: auth
  name: auth
  namespace: currently-working-on-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: auth
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.network/supabase-default: "true"
        io.kompose.service: auth
    spec:
      containers:
        - env:
            - name: API_EXTERNAL_URL
              valueFrom:
                configMapKeyRef:
                  name: supabase-config-map
                  key: API_EXTERNAL_URL
            - name: GOTRUE_API_HOST
              value: 0.0.0.0
            - name: GOTRUE_API_PORT
              value: "9999"
            - name: GOTRUE_DB_DATABASE_URL
              value: postgres://supabase_auth_admin:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
            - name: GOTRUE_DB_DRIVER
              value: postgres
            - name: GOTRUE_DISABLE_SIGNUP
              valueFrom:
                configMapKeyRef:
                  name: supabase-config-map
                  key: DISABLE_SIGNUP
            - name: GOTRUE_EXTERNAL_ANONYMOUS_USERS_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: supabase-config-map
                  key: ENABLE_ANONYMOUS_USERS
            - name: GOTRUE_EXTERNAL_EMAIL_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: supabase-config-map
                  key: ENABLE_EMAIL_SIGNUP
            - name: GOTRUE_EXTERNAL_PHONE_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: supabase-config-map
                  key: ENABLE_PHONE_SIGNUP
            - name: GOTRUE_JWT_ADMIN_ROLES
              value: service_role
            - name: GOTRUE_JWT_AUD
              value: authenticated
            - name: GOTRUE_JWT_DEFAULT_GROUP_NAME
              value: authenticated
            - name: GOTRUE_JWT_EXP
              valueFrom:
                configMapKeyRef:
                  name: supabase-config-map
                  key: JWT_EXPIRY
            - name: GOTRUE_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: supabase-secret
                  key: JWT_SECRET
            - name: GOTRUE_MAILER_AUTOCONFIRM
              valueFrom:
                configMapKeyRef:
                  name: supabase-config-map
                  key: ENABLE_EMAIL_AUTOCONFIRM
            - name: GOTRUE_MAILER_URLPATHS_CONFIRMATION
              valueFrom:
                configMapKeyRef:
                  name: supabase-config-map
                  key: MAILER_URLPATHS_CONFIRMATION
            - name: GOTRUE_MAILER_URLPATHS_EMAIL_CHANGE
              valueFrom:
                configMapKeyRef:
                  name: supabase-config-map
                  key: MAILER_URLPATHS_EMAIL_CHANGE
            - name: GOTRUE_MAILER_URLPATHS_INVITE
              valueFrom:
                configMapKeyRef:
                  name: supabase-config-map
                  key: MAILER_URLPATHS_INVITE
            - name: GOTRUE_MAILER_URLPATHS_RECOVERY
              valueFrom:
                configMapKeyRef:
                  name: supabase-config-map
                  key: MAILER_URLPATHS_RECOVERY
            - name: GOTRUE_SITE_URL
              valueFrom:
                configMapKeyRef:
                  name: supabase-config-map
                  key: SITE_URL
            - name: GOTRUE_SMS_AUTOCONFIRM
              valueFrom:
                configMapKeyRef:
                  name: supabase-config-map
                  key: ENABLE_PHONE_AUTOCONFIRM
            - name: GOTRUE_SMTP_ADMIN_EMAIL
              valueFrom:
                configMapKeyRef:
                  name: supabase-config-map
                  key: SMTP_ADMIN_EMAIL
            - name: GOTRUE_SMTP_HOST
              valueFrom:
                configMapKeyRef:
                  name: supabase-config-map
                  key: SMTP_HOST
            - name: GOTRUE_SMTP_PASS
              valueFrom:
                secretKeyRef:
                  name: supabase-secret
                  key: SMTP_PASS
            - name: GOTRUE_SMTP_PORT
              valueFrom:
                configMapKeyRef:
                  name: supabase-config-map
                  key: SMTP_PORT
            - name: GOTRUE_SMTP_SENDER_NAME
              valueFrom:
                configMapKeyRef:
                  name: supabase-config-map
                  key: SMTP_SENDER_NAME
            - name: GOTRUE_SMTP_USER
              valueFrom:
                configMapKeyRef:
                  name: supabase-config-map
                  key: SMTP_USER
            - name: GOTRUE_URI_ALLOW_LIST
              valueFrom:
                configMapKeyRef:
                  name: supabase-config-map
                  key: ADDITIONAL_REDIRECT_URLS
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: supabase-config-map
                  key: POSTGRES_DB
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: supabase-config-map
                  key: POSTGRES_HOST
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: supabase-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: supabase-config-map
                  key: POSTGRES_PORT
          image: supabase/gotrue:v2.158.1
          livenessProbe:
            exec:
              command:
                - wget
                - --no-verbose
                - --tries=1
                - --spider
                - http://localhost:9999/health
            failureThreshold: 3
            periodSeconds: 5
            timeoutSeconds: 5
          name: supabase-auth
          resources: {}
      restartPolicy: Always
status: {}
