---
# Source: supabase/templates/auth/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: supabase-supabase-auth
  namespace: currently-working-on-db
  labels:
    helm.sh/chart: supabase-0.0.2
    app.kubernetes.io/name: supabase
    app.kubernetes.io/instance: supabase
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: supabase-auth
      app.kubernetes.io/instance: supabase
  template:
    metadata:
      labels:
        app.kubernetes.io/name: supabase-auth
        app.kubernetes.io/instance: supabase
    spec:
      serviceAccountName: supabase-supabase-auth
      securityContext:
        {}
      containers:
        - name: supabase-auth
          securityContext:
            {}
          image: "supabase/gotrue:latest"
          imagePullPolicy: IfNotPresent
          env:
            - name: DB_DRIVER
              valueFrom:
                configMapKeyRef:
                  name: supabase-supabase-auth
                  key: DB_DRIVER
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: supabase-supabase-auth
                  key: DB_HOST
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: supabase-supabase-auth
                  key: DB_NAME
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: supabase-supabase-auth
                  key: DB_PORT
            - name: DB_SSL
              valueFrom:
                configMapKeyRef:
                  name: supabase-supabase-auth
                  key: DB_SSL
            - name: GOTRUE_API_HOST
              valueFrom:
                configMapKeyRef:
                  name: supabase-supabase-auth
                  key: GOTRUE_API_HOST
            - name: GOTRUE_API_PORT
              valueFrom:
                configMapKeyRef:
                  name: supabase-supabase-auth
                  key: GOTRUE_API_PORT
            - name: GOTRUE_DISABLE_SIGNUP
              valueFrom:
                configMapKeyRef:
                  name: supabase-supabase-auth
                  key: GOTRUE_DISABLE_SIGNUP
            - name: GOTRUE_EXTERNAL_EMAIL_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: supabase-supabase-auth
                  key: GOTRUE_EXTERNAL_EMAIL_ENABLED
            - name: GOTRUE_EXTERNAL_PHONE_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: supabase-supabase-auth
                  key: GOTRUE_EXTERNAL_PHONE_ENABLED
            - name: GOTRUE_JWT_ADMIN_ROLES
              valueFrom:
                configMapKeyRef:
                  name: supabase-supabase-auth
                  key: GOTRUE_JWT_ADMIN_ROLES
            - name: GOTRUE_JWT_AUD
              valueFrom:
                configMapKeyRef:
                  name: supabase-supabase-auth
                  key: GOTRUE_JWT_AUD
            - name: GOTRUE_JWT_DEFAULT_GROUP_NAME
              valueFrom:
                configMapKeyRef:
                  name: supabase-supabase-auth
                  key: GOTRUE_JWT_DEFAULT_GROUP_NAME
            - name: GOTRUE_JWT_EXP
              valueFrom:
                configMapKeyRef:
                  name: supabase-supabase-auth
                  key: GOTRUE_JWT_EXP
            - name: GOTRUE_MAILER_AUTOCONFIRM
              valueFrom:
                configMapKeyRef:
                  name: supabase-supabase-auth
                  key: GOTRUE_MAILER_AUTOCONFIRM
            - name: GOTRUE_MAILER_URLPATHS_CONFIRMATION
              valueFrom:
                configMapKeyRef:
                  name: supabase-supabase-auth
                  key: GOTRUE_MAILER_URLPATHS_CONFIRMATION
            - name: GOTRUE_MAILER_URLPATHS_EMAIL_CHANGE
              valueFrom:
                configMapKeyRef:
                  name: supabase-supabase-auth
                  key: GOTRUE_MAILER_URLPATHS_EMAIL_CHANGE
            - name: GOTRUE_MAILER_URLPATHS_INVITE
              valueFrom:
                configMapKeyRef:
                  name: supabase-supabase-auth
                  key: GOTRUE_MAILER_URLPATHS_INVITE
            - name: GOTRUE_MAILER_URLPATHS_RECOVERY
              valueFrom:
                configMapKeyRef:
                  name: supabase-supabase-auth
                  key: GOTRUE_MAILER_URLPATHS_RECOVERY
            - name: GOTRUE_SITE_URL
              valueFrom:
                configMapKeyRef:
                  name: supabase-supabase-auth
                  key: GOTRUE_SITE_URL
            - name: GOTRUE_SMS_AUTOCONFIRM
              valueFrom:
                configMapKeyRef:
                  name: supabase-supabase-auth
                  key: GOTRUE_SMS_AUTOCONFIRM
            - name: GOTRUE_SMTP_ADMIN_EMAIL
              valueFrom:
                configMapKeyRef:
                  name: supabase-supabase-auth
                  key: GOTRUE_SMTP_ADMIN_EMAIL
            - name: GOTRUE_SMTP_HOST
              valueFrom:
                configMapKeyRef:
                  name: supabase-supabase-auth
                  key: GOTRUE_SMTP_HOST
            - name: GOTRUE_SMTP_PORT
              valueFrom:
                configMapKeyRef:
                  name: supabase-supabase-auth
                  key: GOTRUE_SMTP_PORT
            - name: GOTRUE_SMTP_SENDER_NAME
              valueFrom:
                configMapKeyRef:
                  name: supabase-supabase-auth
                  key: GOTRUE_SMTP_SENDER_NAME
            - name: GOTRUE_URI_ALLOW_LIST
              valueFrom:
                configMapKeyRef:
                  name: supabase-supabase-auth
                  key: GOTRUE_URI_ALLOW_LIST
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: supabase-secret
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: supabase-secret
                  key: DB_PASSWORD
            - name: GOTRUE_DB_DATABASE_URL
              value: $(DB_DRIVER)://$(DB_USER):$(DB_PASSWORD)@$(DB_HOST):$(DB_PORT)/$(DB_NAME)?search_path=auth&sslmode=$(DB_SSL)
            - name: GOTRUE_DB_DRIVER
              value: $(DB_DRIVER)
            - name: GOTRUE_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: supabase-secret
                  key: JWT_SECRET
            - name: GOTRUE_SMTP_USER
              valueFrom:
                secretKeyRef:
                  name: supabase-secret
                  key: SMTP_USERNAME
            - name: GOTRUE_SMTP_PASS
              valueFrom:
                secretKeyRef:
                  name: supabase-secret
                  key: SMTP_PASSWORD
          ports:
            - name: http
              containerPort: 9999
              protocol: TCP
