apiVersion: v1
kind: ConfigMap
metadata:
  name: supabase-config-map
  namespace: currently-working-on-db
data:
  POSTGRES_HOST: db
  POSTGRES_DB: postgres
  POSTGRES_PORT: "5432
  KONG_HTTP_PORT: "8000"
  KONG_HTTPS_PORT: "8443"
  PGRST_DB_SCHEMAS: public,storage,graphql_public
  SITE_URL: http://localhost:3000
  ADDITIONAL_REDIRECT_URLS: ""
  JWT_EXPIRY: "3600"
  DISABLE_SIGNUP: "false"
  API_EXTERNAL_URL: http://localhost:8000
  MAILER_URLPATHS_CONFIRMATION: /auth/v1/verify
  MAILER_URLPATHS_INVITE: /auth/v1/verify
  MAILER_URLPATHS_RECOVERY: /auth/v1/verify
  MAILER_URLPATHS_EMAIL_CHANGE: /auth/v1/verify
  ENABLE_EMAIL_SIGNUP: "true"
  ENABLE_EMAIL_AUTOCONFIRM: "false"
  SMTP_ADMIN_EMAIL: admin@example.com
  SMTP_HOST: supabase-mail
  SMTP_PORT: "2500"
  SMTP_USER: fake_mail_user
  SMTP_SENDER_NAME: fake_sender
  ENABLE_ANONYMOUS_USERS: "false"
  ENABLE_PHONE_SIGNUP: "true"
  ENABLE_PHONE_AUTOCONFIRM: "true"
  STUDIO_DEFAULT_ORGANIZATION: Default Organization
  STUDIO_DEFAULT_PROJECT: Default Project
  STUDIO_PORT: "3000"
  SUPABASE_PUBLIC_URL: http://localhost:8000
  IMGPROXY_ENABLE_WEBP_DETECTION: "true"
  FUNCTIONS_VERIFY_JWT: "false"
  DOCKER_SOCKET_LOCATION: /var/run/docker.sock
  GOOGLE_PROJECT_ID: GOOGLE_PROJECT_ID
  GOOGLE_PROJECT_NUMBER: GOOGLE_PROJECT_NUMBER
