apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: db
  name: db
  namespace: currently-working-on-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: db
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.network/supabase-default: "true"
        io.kompose.service: db
    spec:
      containers:
        - args:
            - postgres
            - -c
            - config_file=/etc/postgresql/postgresql.conf
            - -c
            - log_min_messages=fatal
          env:
            - name: JWT_EXP
              valueFrom:
                configMapKeyRef:
                  name: supabase-config-map
                  key: JWT_EXPIRY
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: supabase-secret
                  key: JWT_SECRET
            - name: PGDATABASE
              valueFrom:
                configMapKeyRef:
                  name: supabase-config-map
                  key: POSTGRES_DB
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: supabase-secret
                  key: POSTGRES_PASSWORD
            - name: PGPORT
              valueFrom:
                configMapKeyRef:
                  name: supabase-config-map
                  key: POSTGRES_PORT
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: supabase-config-map
                  key: POSTGRES_DB
            - name: POSTGRES_HOST
              value: /var/run/postgresql
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: supabase-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: supabase-config-map
                  key: POSTGRES_PORT
          image: supabase/postgres:15.1.1.78
          livenessProbe:
            exec:
              command:
                - pg_isready -U postgres -h localhost
            failureThreshold: 10
            periodSeconds: 5
            timeoutSeconds: 5
          name: supabase-db
          ports:
            - containerPort: 5432
              hostPort: 5432
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d/migrations/99-realtime.sql
              name: db-claim0
            - mountPath: /docker-entrypoint-initdb.d/init-scripts/98-webhooks.sql
              name: db-claim1
            - mountPath: /docker-entrypoint-initdb.d/init-scripts/99-roles.sql
              name: db-claim2
            - mountPath: /docker-entrypoint-initdb.d/init-scripts/99-jwt.sql
              name: db-claim3
            - mountPath: /var/lib/postgresql/data
              name: db-claim4
            - mountPath: /docker-entrypoint-initdb.d/migrations/99-logs.sql
              name: db-claim5
            - mountPath: /etc/postgresql-custom
              name: db-config
      restartPolicy: Always
      volumes:
        - name: db-claim0
          persistentVolumeClaim:
            claimName: db-claim0
        - name: db-claim1
          persistentVolumeClaim:
            claimName: db-claim1
        - name: db-claim2
          persistentVolumeClaim:
            claimName: db-claim2
        - name: db-claim3
          persistentVolumeClaim:
            claimName: db-claim3
        - name: db-claim4
          persistentVolumeClaim:
            claimName: db-claim4
        - name: db-claim5
          persistentVolumeClaim:
            claimName: db-claim5
        - name: db-config
          persistentVolumeClaim:
            claimName: db-config
status: {}
