apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: functions
  name: functions
  namespace: currently-working-on-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: functions
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.network/supabase-default: "true"
        io.kompose.service: functions
    spec:
      containers:
        - args:
            - start
            - --main-service
            - /home/deno/functions/main
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: supabase-secret
                  key: JWT_SECRET
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: supabase-config-map
                  key: POSTGRES_DB
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: supabase-config-map
                  key: POSTGRES_HOST
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: supabase-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: supabase-config-map
                  key: POSTGRES_PORT
            - name: SUPABASE_ANON_KEY
              valueFrom:
                secretKeyRef:
                  name: supabase-secret
                  key: ANON_KEY
            - name: SUPABASE_DB_URL
              value: postgresql://postgres:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
            - name: SUPABASE_SERVICE_ROLE_KEY
              valueFrom:
                secretKeyRef:
                  name: supabase-secret
                  key: SERVICE_ROLE_KEY
            - name: SUPABASE_URL
              value: http://kong:8000
            - name: VERIFY_JWT
              valueFrom:
                configMapKeyRef:
                  name: supabase-config-map
                  key: FUNCTIONS_VERIFY_JWT
          image: supabase/edge-runtime:v1.56.0
          name: supabase-edge-functions
          resources: {}
          volumeMounts:
            - mountPath: /home/deno/functions
              name: functions-claim0
      restartPolicy: Always
      volumes:
        - name: functions-claim0
          persistentVolumeClaim:
            claimName: functions-claim0
status: {}
