apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: imgproxy
  name: imgproxy
  namespace: currently-working-on-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: imgproxy
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.network/supabase-default: "true"
        io.kompose.service: imgproxy
    spec:
      containers:
        - env:
            - name: IMGPROXY_BIND
              value: :5001
            - name: IMGPROXY_ENABLE_WEBP_DETECTION
              valueFrom:
                configMapKeyRef:
                  name: supabase-config-map
                  key: IMGPROXY_ENABLE_WEBP_DETECTION
            - name: IMGPROXY_LOCAL_FILESYSTEM_ROOT
              value: /
            - name: IMGPROXY_USE_ETAG
              value: "true"
          image: darthsim/imgproxy:v3.8.0
          livenessProbe:
            exec:
              command:
                - imgproxy
                - health
            failureThreshold: 3
            periodSeconds: 5
            timeoutSeconds: 5
          name: supabase-imgproxy
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/storage
              name: imgproxy-claim0
      restartPolicy: Always
      volumes:
        - name: imgproxy-claim0
          persistentVolumeClaim:
            claimName: imgproxy-claim0
status: {}
