apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
    name: currently-working-on-db
    namespace: currently-working-on-db
spec:
    secretName: currently-working-on-db
    issuerRef:
        name: acme-issuer
        kind: ClusterIssuer
    dnsNames:
        - "currently-working-on-db.trueberryless.org"
