---
# Source: supabase/templates/kong/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: supabase-supabase-kong
  namespace: currently-working-on-db
  labels:
    helm.sh/chart: supabase-0.0.2
    app.kubernetes.io/name: supabase
    app.kubernetes.io/instance: supabase
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: supabase-kong
      app.kubernetes.io/instance: supabase
  template:
    metadata:
      labels:
        app.kubernetes.io/name: supabase-kong
        app.kubernetes.io/instance: supabase
    spec:
      serviceAccountName: supabase-supabase-kong
      securityContext:
        {}
      containers:
        - name: supabase-kong
          securityContext:
            {}
          image: "kong:latest"
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh"]
          args: ["/scripts/wrapper.sh"]
          env:
            - name: KONG_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: supabase-supabase-kong
                  key: KONG_DATABASE
            - name: KONG_DECLARATIVE_CONFIG
              valueFrom:
                configMapKeyRef:
                  name: supabase-supabase-kong
                  key: KONG_DECLARATIVE_CONFIG
            - name: KONG_DNS_ORDER
              valueFrom:
                configMapKeyRef:
                  name: supabase-supabase-kong
                  key: KONG_DNS_ORDER
            - name: KONG_PLUGINS
              valueFrom:
                configMapKeyRef:
                  name: supabase-supabase-kong
                  key: KONG_PLUGINS
            - name: SUPABASE_ANON_KEY
              valueFrom:
                secretKeyRef:
                  name: supabase-secret
                  key: ANON_KEY
            - name: SUPABASE_SERVICE_KEY
              valueFrom:
                secretKeyRef:
                  name: supabase-secret
                  key: SERVICE_ROLE_KEY
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          volumeMounts:
            - mountPath: /home/kong/template.yml
              name: config
              subPath: template.yml
            - mountPath: /scripts
              name: wrapper
      volumes:
        - name: config
          configMap:
            name: supabase-supabase-kong
            defaultMode: 0777
            items:
            - key: template.yml
              path: template.yml
        - name: wrapper
          configMap:
            name: supabase-supabase-kong
            defaultMode: 0777
            items:
            - key: wrapper.sh
              path: wrapper.sh
