---
# Source: supabase/templates/kong/config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: supabase-supabase-kong
  namespace: currently-working-on-db
  labels:
    helm.sh/chart: supabase-0.0.2
    app.kubernetes.io/name: supabase
    app.kubernetes.io/instance: supabase
    app.kubernetes.io/managed-by: Helm
data:
  KONG_DATABASE: "off"
  KONG_DECLARATIVE_CONFIG: /home/kong/kong.yml
  KONG_DNS_ORDER: LAST,A,CNAME
  KONG_PLUGINS: request-transformer,cors,key-auth,acl
  wrapper.sh: |
    #!/bin/sh

    set -euo pipefail

    echo "Replacing env placeholders of /home/kong/kong.yml"

    sed \
    -e "s/\${SUPABASE_ANON_KEY}/${SUPABASE_ANON_KEY}/" \
    -e "s/\${SUPABASE_SERVICE_KEY}/${SUPABASE_SERVICE_KEY}/" \
    /home/kong/template.yml \
    > /home/kong/kong.yml

    exec /docker-entrypoint.sh kong docker-start
  template.yml: |
    _format_version: "1.1"

    consumers:
      - username: anon
        keyauth_credentials:
            - key: ${SUPABASE_ANON_KEY}
      - username: service_role
        keyauth_credentials:
            - key: ${SUPABASE_SERVICE_KEY}

    acls:
      - consumer: anon
        group: anon
      - consumer: service_role
        group: admin

    services:
      - name: auth-v1-open
        url: http://supabase-supabase-auth.default.svc.cluster.local:9999/verify
        routes:
          - name: auth-v1-open
            strip_path: true
            paths:
              - /auth/v1/verify
        plugins:
          - name: cors
      - name: auth-v1-open-callback
        url: http://supabase-supabase-auth.default.svc.cluster.local:9999/callback
        routes:
          - name: auth-v1-open-callback
            strip_path: true
            paths:
              - /auth/v1/callback
        plugins:
          - name: cors
      - name: auth-v1-open-authorize
        url: http://supabase-supabase-auth.default.svc.cluster.local:9999/authorize
        routes:
          - name: auth-v1-open-authorize
            strip_path: true
            paths:
              - /auth/v1/authorize
        plugins:
          - name: cors


      - name: auth-v1
        _comment: "GoTrue: /auth/v1/* -> http://supabase-supabase-auth.default.svc.cluster.local:9999/*"
        url: http://supabase-supabase-auth.default.svc.cluster.local:9999
        routes:
          - name: auth-v1-all
            strip_path: true
            paths:
              - /auth/v1/
        plugins:
          - name: cors
          - name: key-auth
            config:
              hide_credentials: false
          - name: acl
            config:
              hide_groups_header: true
              allow:
                - admin
                - anon


      - name: rest-v1
        _comment: "PostgREST: /rest/v1/* -> http://supabase-supabase-rest.default:3000/*"
        url: http://supabase-supabase-rest.default:3000/
        routes:
          - name: rest-v1-all
            strip_path: true
            paths:
              - /rest/v1/
        plugins:
          - name: cors
          - name: key-auth
            config:
              hide_credentials: true
          - name: acl
            config:
              hide_groups_header: true
              allow:
                - admin
                - anon

      - name: realtime-v1
        _comment: "Realtime: /realtime/v1/* -> ws://supabase-supabase-realtime.default.svc.cluster.local:4000/socket/*"
        url: http://supabase-supabase-realtime.default.svc.cluster.local:4000/socket
        routes:
          - name: realtime-v1-all
            strip_path: true
            paths:
              - /realtime/v1/
        plugins:
          - name: cors
          - name: key-auth
            config:
              hide_credentials: false
          - name: acl
            config:
              hide_groups_header: true
              allow:
                - admin
                - anon

      - name: storage-v1
        _comment: "Storage: /storage/v1/* -> http://supabase-supabase-storage.default.svc.cluster.local:5000/*"
        url: http://supabase-supabase-storage.default.svc.cluster.local:5000/
        routes:
          - name: storage-v1-all
            strip_path: true
            paths:
              - /storage/v1/
        plugins:
          - name: cors

      - name: meta
        _comment: "pg-meta: /pg/* -> http://supabase-supabase-meta.default.svc.cluster.local:8080/*"
        url: http://supabase-supabase-meta.default.svc.cluster.local:8080/
        routes:
          - name: meta-all
            strip_path: true
            paths:
              - /pg/
        plugins:
          - name: key-auth
            config:
              hide_credentials: false
          - name: acl
            config:
              hide_groups_header: true
              allow:
                - admin
