apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: kong
  name: kong
  namespace: currently-working-on-db
spec:
  ports:
    - name: "8000"
      port: 8000
      targetPort: 8000
    - name: "8443"
      port: 8443
      targetPort: 8443
  selector:
    io.kompose.service: kong
status:
  loadBalancer: {}
