---
# Source: supabase/templates/meta/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: supabase-supabase-meta
  namespace: currently-working-on-db
  labels:
    helm.sh/chart: supabase-0.0.2
    app.kubernetes.io/name: supabase
    app.kubernetes.io/instance: supabase
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: supabase-meta
      app.kubernetes.io/instance: supabase
  template:
    metadata:
      labels:
        app.kubernetes.io/name: supabase-meta
        app.kubernetes.io/instance: supabase
    spec:
      serviceAccountName: supabase-supabase-meta
      securityContext:
        {}
      containers:
        - name: supabase-meta
          securityContext:
            {}
          image: "supabase/postgres-meta:latest"
          imagePullPolicy: IfNotPresent
          env:
            - name: DB_DRIVER
              valueFrom:
                configMapKeyRef:
                  name: supabase-supabase-meta
                  key: DB_DRIVER
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: supabase-supabase-meta
                  key: DB_HOST
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: supabase-supabase-meta
                  key: DB_NAME
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: supabase-supabase-meta
                  key: DB_PORT
            - name: DB_SSL
              valueFrom:
                configMapKeyRef:
                  name: supabase-supabase-meta
                  key: DB_SSL
            - name: PG_META_PORT
              valueFrom:
                configMapKeyRef:
                  name: supabase-supabase-meta
                  key: PG_META_PORT
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: supabase-secret
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: supabase-secret
                  key: DB_PASSWORD
            - name: PG_META_DB_HOST
              value: $(DB_HOST)
            - name: PG_META_DB_PORT
              value: $(DB_PORT)
            - name: PG_META_DB_NAME
              value: $(DB_NAME)
            - name: PG_META_DB_USER
              value: $(DB_USER)
            - name: PG_META_DB_PASSWORD
              value: $(DB_PASSWORD)
            - name: PG_META_DB_SSL_MODE
              value: $(DB_SSL)
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
