apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: meta
  name: meta
  namespace: currently-working-on-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: meta
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.network/supabase-default: "true"
        io.kompose.service: meta
    spec:
      containers:
        - env:
            - name: PG_META_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: supabase-config-map
                  key: POSTGRES_HOST
            - name: PG_META_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: supabase-config-map
                  key: POSTGRES_DB
            - name: PG_META_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: supabase-secret
                  key: POSTGRES_PASSWORD
            - name: PG_META_DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: supabase-config-map
                  key: POSTGRES_PORT
            - name: PG_META_DB_USER
              value: supabase_admin
            - name: PG_META_PORT
              value: "8080"
          image: supabase/postgres-meta:v0.83.2
          name: supabase-meta
          resources: {}
      restartPolicy: Always
status: {}
