---
# Source: supabase/templates/realtime/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: supabase-supabase-realtime
  namespace: currently-working-on-db
  labels:
    helm.sh/chart: supabase-0.0.2
    app.kubernetes.io/name: supabase
    app.kubernetes.io/instance: supabase
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: supabase-realtime
      app.kubernetes.io/instance: supabase
  template:
    metadata:
      labels:
        app.kubernetes.io/name: supabase-realtime
        app.kubernetes.io/instance: supabase
    spec:
      serviceAccountName: supabase-supabase-realtime
      securityContext:
        {}
      containers:
        - name: supabase-realtime
          securityContext:
            {}
          image: "supabase/realtime:latest"
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh"]
          args: ["-c", "/app/bin/migrate && /app/bin/realtime eval 'Realtime.Release.seeds(Realtime.Repo)' && /app/bin/server"]
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: supabase-supabase-realtime
                  key: DB_HOST
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: supabase-supabase-realtime
                  key: DB_NAME
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: supabase-supabase-realtime
                  key: DB_PORT
            - name: DB_SSL
              valueFrom:
                configMapKeyRef:
                  name: supabase-supabase-realtime
                  key: DB_SSL
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: supabase-supabase-realtime
                  key: PORT
            - name: REPLICATION_MODE
              valueFrom:
                configMapKeyRef:
                  name: supabase-supabase-realtime
                  key: REPLICATION_MODE
            - name: REPLICATION_POLL_INTERVAL
              valueFrom:
                configMapKeyRef:
                  name: supabase-supabase-realtime
                  key: REPLICATION_POLL_INTERVAL
            - name: SECURE_CHANNELS
              valueFrom:
                configMapKeyRef:
                  name: supabase-supabase-realtime
                  key: SECURE_CHANNELS
            - name: SLOT_NAME
              valueFrom:
                configMapKeyRef:
                  name: supabase-supabase-realtime
                  key: SLOT_NAME
            - name: TEMPORARY_SLOT
              valueFrom:
                configMapKeyRef:
                  name: supabase-supabase-realtime
                  key: TEMPORARY_SLOT
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: supabase-secret
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: supabase-secret
                  key: DB_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: supabase-secret
                  key: JWT_SECRET
            - name: API_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: supabase-secret
                  key: JWT_SECRET
          ports:
            - name: http
              containerPort: 4000
              protocol: TCP
