---
# Source: supabase/templates/rest/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: supabase-supabase-rest
  namespace: currently-working-on-db
  labels:
    helm.sh/chart: supabase-0.0.2
    app.kubernetes.io/name: supabase
    app.kubernetes.io/instance: supabase
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: supabase-rest
      app.kubernetes.io/instance: supabase
  template:
    metadata:
      labels:
        app.kubernetes.io/name: supabase-rest
        app.kubernetes.io/instance: supabase
    spec:
      serviceAccountName: supabase-supabase-rest
      securityContext:
        {}
      containers:
        - name: supabase-rest
          securityContext:
            {}
          image: "postgrest/postgrest:latest"
          imagePullPolicy: IfNotPresent
          env:
            - name: DB_DRIVER
              valueFrom:
                configMapKeyRef:
                  name: supabase-supabase-rest
                  key: DB_DRIVER
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: supabase-supabase-rest
                  key: DB_HOST
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: supabase-supabase-rest
                  key: DB_NAME
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: supabase-supabase-rest
                  key: DB_PORT
            - name: DB_SSL
              valueFrom:
                configMapKeyRef:
                  name: supabase-supabase-rest
                  key: DB_SSL
            - name: PGRST_DB_ANON_ROLE
              valueFrom:
                configMapKeyRef:
                  name: supabase-supabase-rest
                  key: PGRST_DB_ANON_ROLE
            - name: PGRST_DB_SCHEMA
              valueFrom:
                configMapKeyRef:
                  name: supabase-supabase-rest
                  key: PGRST_DB_SCHEMA
            - name: PGRST_DB_USE_LEGACY_GUCS
              valueFrom:
                configMapKeyRef:
                  name: supabase-supabase-rest
                  key: PGRST_DB_USE_LEGACY_GUCS
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: supabase-secret
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: supabase-secret
                  key: DB_PASSWORD
            - name: PGRST_DB_URI
              value: $(DB_DRIVER)://$(DB_USER):$(DB_PASSWORD)@$(DB_HOST):$(DB_PORT)/$(DB_NAME)?sslmode=$(DB_SSL)
            - name: PGRST_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: supabase-secret
                  key: JWT_SECRET
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
