---
# Source: supabase/templates/storage/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: supabase-supabase-storage
  namespace: currently-working-on-db
  labels:
    helm.sh/chart: supabase-0.0.2
    app.kubernetes.io/name: supabase
    app.kubernetes.io/instance: supabase
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: supabase-storage
      app.kubernetes.io/instance: supabase
  template:
    metadata:
      labels:
        app.kubernetes.io/name: supabase-storage
        app.kubernetes.io/instance: supabase
    spec:
      restartPolicy: Always
      serviceAccountName: supabase-supabase-storage
      securityContext:
        {}
      containers:
        - name: supabase-storage
          securityContext:
            {}
          image: "supabase/storage-api:latest"
          imagePullPolicy: IfNotPresent
          env:
            - name: DB_DRIVER
              valueFrom:
                configMapKeyRef:
                  name: supabase-supabase-storage
                  key: DB_DRIVER
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: supabase-supabase-storage
                  key: DB_HOST
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: supabase-supabase-storage
                  key: DB_NAME
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: supabase-supabase-storage
                  key: DB_PORT
            - name: DB_SSL
              valueFrom:
                configMapKeyRef:
                  name: supabase-supabase-storage
                  key: DB_SSL
            - name: FILE_SIZE_LIMIT
              valueFrom:
                configMapKeyRef:
                  name: supabase-supabase-storage
                  key: FILE_SIZE_LIMIT
            - name: FILE_STORAGE_BACKEND_PATH
              valueFrom:
                configMapKeyRef:
                  name: supabase-supabase-storage
                  key: FILE_STORAGE_BACKEND_PATH
            - name: GLOBAL_S3_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: supabase-supabase-storage
                  key: GLOBAL_S3_BUCKET
            - name: PGOPTIONS
              valueFrom:
                configMapKeyRef:
                  name: supabase-supabase-storage
                  key: PGOPTIONS
            - name: POSTGREST_URL
              valueFrom:
                configMapKeyRef:
                  name: supabase-supabase-storage
                  key: POSTGREST_URL
            - name: REGION
              valueFrom:
                configMapKeyRef:
                  name: supabase-supabase-storage
                  key: REGION
            - name: STORAGE_BACKEND
              valueFrom:
                configMapKeyRef:
                  name: supabase-supabase-storage
                  key: STORAGE_BACKEND
            - name: TENANT_ID
              valueFrom:
                configMapKeyRef:
                  name: supabase-supabase-storage
                  key: TENANT_ID
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: supabase-secret
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: supabase-secret
                  key: DB_PASSWORD
            - name: DATABASE_URL
              value: $(DB_DRIVER)://$(DB_USER):$(DB_PASSWORD)@$(DB_HOST):$(DB_PORT)/$(DB_NAME)?search_path=auth&sslmode=$(DB_SSL)
            - name: PGRST_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: supabase-secret
                  key: JWT_SECRET
            - name: ANON_KEY
              valueFrom:
                secretKeyRef:
                  name: supabase-secret
                  key: ANON_KEY
            - name: SERVICE_KEY
              valueFrom:
                secretKeyRef:
                  name: supabase-secret
                  key: SERVICE_ROLE_KEY
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
      volumes:
