---
# Source: supabase/templates/studio/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: supabase-supabase-studio
  namespace: currently-working-on-db
  labels:
    helm.sh/chart: supabase-0.0.2
    app.kubernetes.io/name: supabase
    app.kubernetes.io/instance: supabase
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: supabase-studio
      app.kubernetes.io/instance: supabase
  template:
    metadata:
      labels:
        app.kubernetes.io/name: supabase-studio
        app.kubernetes.io/instance: supabase
    spec:
      serviceAccountName: supabase-supabase-studio
      securityContext:
        {}
      containers:
        - name: supabase-studio
          securityContext:
            {}
          image: "supabase/studio:latest"
          imagePullPolicy: IfNotPresent
          env:
            - name: STUDIO_PG_META_URL
              valueFrom:
                configMapKeyRef:
                  name: supabase-supabase-studio
                  key: STUDIO_PG_META_URL
            - name: SUPABASE_REST_URL
              valueFrom:
                configMapKeyRef:
                  name: supabase-supabase-studio
                  key: SUPABASE_REST_URL
            - name: SUPABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: supabase-supabase-studio
                  key: SUPABASE_URL
            - name: SUPABASE_ANON_KEY
              valueFrom:
                secretKeyRef:
                  name: supabase-secret
                  key: ANON_KEY
            - name: SUPABASE_SERVICE_KEY
              valueFrom:
                secretKeyRef:
                  name: supabase-secret
                  key: SERVICE_ROLE_KEY
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
