apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: vector
  name: vector
  namespace: currently-working-on-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: vector
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.network/supabase-default: "true"
        io.kompose.service: vector
    spec:
      containers:
        - args:
            - --config
            - etc/vector/vector.yml
          env:
            - name: LOGFLARE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: supabase-secret
                  key: LOGFLARE_API_KEY
          image: timberio/vector:0.28.1-alpine
          livenessProbe:
            exec:
              command:
                - wget
                - --no-verbose
                - --tries=1
                - --spider
                - http://vector:9001/health
            failureThreshold: 3
            periodSeconds: 5
            timeoutSeconds: 5
          name: supabase-vector
          resources: {}
          volumeMounts:
            - mountPath: /etc/vector/vector.yml
              name: vector-claim0
              readOnly: true
            - mountPath: /var/run/docker.sock
              name: vector-claim1
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: vector-claim0
          persistentVolumeClaim:
            claimName: vector-claim0
            readOnly: true
        - name: vector-claim1
          persistentVolumeClaim:
            claimName: vector-claim1
            readOnly: true
status: {}
