apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: vector-claim0
  name: vector-claim0
  namespace: currently-working-on-db
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 100Mi
  storageClassName: manual
  volumeName: currently-working-on-db-vector-pv0
status: {}
